### ISSUE TITLE
url demo or screenshot

### ISSUE THREAD

**Issue by johnfelipe** [leowmjw/parliamentMY-QA-blast#1]
Tnks

**Comment by leowmjw** [comment]
Thanks @johnfelipe for the great suggestion; I've updated the document (as part of the new release) to include your idea!

Demo for the original Q&A Parser:
https://asciinema.org/a/ejts2pcz1h7gq9g0008hv1p8q

Demo for the new Hansard Parser:
https://asciinema.org/a/6rcyjntbh75cyizp7bcr638qe
