### ISSUE TITLE
When run against written replies, soalan-0 intro is wrong, there are no intros.

### ISSUE THREAD

**Issue by kaerumy** [leowmjw/parliamentMY-QA-blast#2]
Possibly need config for whether files are written or oral, so that for written not to treat first page as intro.

**Comment by leowmjw** [comment]
This needs a tweak to the existing Q&A engine.  Now with the new release and the ability to pass it some extra meta parameters; it should not be too difficult to change the behaviour slightly with the given extra meta parameter.

Stay tuned!

**Comment by leowmjw** [comment]
Fixed in latest master; accepts the additional --parser=written
